language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - secure: a5r0YutFmYDXBf0c7qtykVxjjY0SJb4vBvkdcFiKe6bYk85sa2HypwY8g6tkANHJm9uUjbE5UIj2dVF+OLWfV3FhWvVAs/VsW8Fl/1lDhlqEsMKA5A9GXddJvFUu+vSxB3w6FPGArd9UL0hp6vT+lUiLBarUfYHbpxRPqrXWH4vZjvOcfW1epAxSD/x0oIH2lvEaicfDW4CYNTR0L3nmPtOM3UECDbUUYkELyshOLCoiK0tNxJw46Tda/IGncubCF1bxdt6UGIjTv6jI7PEbN2LqgVscDpbi7mEbPq/AW0cxCKXLYLijdLvFK//wDJqD30QosSViUHNAp7xXRGpxeZdh1RK9811NOxLjunYOxR9KQ4VDdFHACH4o25Cod33VJiPT7cmGgLlhRZ+HgEnYAsNbpJLUwU0waWSsAuS1WjsziY3GSS27zf5pldvd5VrPBfvrccrP4pfl1T10K3Qcme/QClh//iEE+bJsc/5Qe4Sit9ES0lguvkaXUjk82xJ3S3pFua9+FOsCKzyeR37cvl751m8m0vo68gy+ZWC02L1ebzV8bhUAU0vJTQuZOWXBLjd5SenQacu2ofU/oTwBsdg0kCBYbG1CdLkO7Otoz7FOYHioY9ljKnDg84MuPnDuISenDXtuhI+eEYh4Tg0CcLYb6LwRdcTSPmxRxRihPes=
    - secure: q+DGF9RxnO4cq73d8fNBI7Lk5aJppMz9JkzhlThrhoIPSUl4qDyYiWUIonWU0ECAVmRfv4YFe8X9s+yy6P2ss+P4kApkxUf4T/QMSxi9bTxWJ1+6ojjFynCaHpo3Ykm1wQ1PjQF/tIBsg0i5F/ZxJGxRythOis0T7Ynro/yZEtmnUMSRXmCjL+BETW56xA/5FUCu19fNhVUfQDBFB4m2i6+tTeZ+ThaqgIiD4mrWjBU+3XZyCt5gm3AoQQU6/TeqE/wZYVXIqipqRsyfnomtVm60fZRKNb+b8/jPhWZS/P8kS3aU4dzmtmJf++eoBTCH05JFPzXpx7wgxHf7z2GJA0hzteeZaVWjdrufdGV/+ZSwefglFN5tIjtsjMAGXN2ig/55PKzHppypAjnUsNtezhEfVtO9ukq2Q2Lxsn4sJyS2YzEVg6fNYnx/BL6XnIihtBKKc1/2w88ObvjTk+Tc5UTtrdcs23pLekQ/f9zYVVtJDbDtgIHQhvS4Cm3EOfdnAXgxxZ4vlJiw6GPej7nquZRCeK39nf3sf63uBkkSO/WqiOE9GZE26phpL7Ws2c4l/iiDZ4sXDUlAGV54PsXnHuiii1DRtDO7FfQwA/JA3p2eK+CNpI3aoqyAEFG9uoI0cIabuX/ZSvd4K8FE3LHp8YXkAJmB/Lawne8BOK4dNUg=
before_script:
  - composer update
script:
  - phpunit --configuration phpunit.xml.dist
